Hw1
antongulikov/CSC.NET2017 pull request #1
Opened 2017-09-08 19:54 UTC by antongulikov

Trie class was implemented.

2017-10-02 02:41 UTC, VMAtm requested changes
На данный момент оценка 9/10

2017-10-02 02:41 UTC, VMAtm commented on hw1/Trie/Test/Properties/AssemblyInfo.cs
> +using System.Runtime.CompilerServices;
Несмотря на то, что это системный файл, созданный не вами, было бы неплохо проверять и его на соответствие стилям - данный импорт в вашем файле не используется

2017-10-02 02:41 UTC, VMAtm commented on hw1/Trie/Test/Test.csproj
> +    <Reference Include="nunit.framework, Version=3.5.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb">
Вы использовали для тестов библиотеку NUnit, и это очень хорошо. Учтите, что для корректной компиляции требуется файл packages.config, с помощью которого NuGet восстанавливает все зависимости в проекте. Несмотря на то, что сам файл присутствует, его нет в файле проекта, не хватает строк:
`  <ItemGroup>
    <None Include="packages.config" />
  </ItemGroup>`
Из-за этого компиляция свежескачанного репозитория не проходит

2017-10-02 02:41 UTC, VMAtm commented on hw1/Trie/Test/Tests.cs
> +        private Trie.Trie _trie;
Из-за одинакового названия пространства имён и класса приходится использовать подобный "некрасивый" импорт. Основной проект, возможно, удобнее было бы назвать Homework1 или схожим именем.

2017-10-02 02:41 UTC, VMAtm commented on hw1/Trie/Test/Tests.cs
> +        public void TestInit()
Что проверяет этот тест?

2017-10-02 02:41 UTC, VMAtm commented on hw1/Trie/Test/Tests.cs
> +    public class Tests
Согласно отчёту dotCover, у вас не покрыты тестами некоторые части кода:
- цикл foreach в методе Remove (с двумя ветками внутреннего if)
- вырожденный случай в методе HowManyStartsWithPrefix
- метод RemoveLink в классе TrieNode

2017-10-02 02:41 UTC, VMAtm commented on hw1/Trie/Test/Tests.cs
> +        }
Здесь и далее: Unit-тесты обычно визуально разделяют на подготовку данных (в том числе ожидаемый результат), выполнений определённых действий и проверку результата, у вас получилось всё в одной строке. Тому, кто будет разбирать ваш код по тестам, будет немного сложно.

2017-10-02 02:41 UTC, VMAtm commented on hw1/Trie/Test/Tests.cs
> +        public void TestAddNonEmptyStrings()
Здесь и далее: Для набора тестовых данных в виде списка удобнее использовать TestCaseSource: https://stackoverflow.com/a/19480201/213550

2017-10-02 02:41 UTC, VMAtm commented on hw1/Trie/Test/Tests.cs
> +        {
В данном методе ожидаемые результаты выглядят как "магические числа", для человека, который видит код в первый раз. Возможно, стоило подсчитывать правильный ответ кодом - создать список входных параметров, и для каждого проверочного случая считать ответ.

2017-10-02 02:41 UTC, VMAtm commented on hw1/Trie/Test/Test.csproj
> +    <Reference Include="System.Data" />
Здесь и далее: некоторые ссылки из шаблона не используются и могут быть спокойно удалены

2017-10-02 02:41 UTC, VMAtm commented on hw1/Trie/Trie/Main.cs
> +    public class MainClass
Данный класс нужен только для того, чтобы Visual Studio создала консольное приложение на основе вашей библиотеки. Можно сменить тип проекта на Class Library, и удалить данный файл.

2017-10-02 02:41 UTC, VMAtm commented on hw1/Trie/Trie/Trie.cs
> +    {
Про совпадение пространства имён и класса было написано выше, здесь же хотел бы отметить следующее: в задании не было прямо сказано, но подразумевалось использование интерфейса для определения методов, которые нужно реализовать. Это простой способ отдать компилятору на проверку, вся ли требуемая функциональность реализована. Так же в этом случае в Unit-тестах можно определять тестируемый класс как ITrie, убирая привязку к конкретной реализации, и покрывая тестами только нужные методы.

2017-10-02 02:41 UTC, VMAtm commented on hw1/Trie/Trie/Trie.cs
> +                if (!currentNode.IsContainLinkWithValue(ch))
Мне кажется, что метод IsContainLinkWithValue избыточен - можно было просто возвращать null в случае отсутствия ключа в узле. Сейчас же обязанность вызвать метод проверки до вызова GetLink ложится на пользователя библиотеки, что может привести к необработанному KeyNotFoundException (кстати, непокрытому тестами). Если убрать этот метод, можно упростить цикл, заменив вызов метода на проверку на null. Отмечу, что метод, возможно, стоит убрать только в этом цикле, в методе Add он, наоборот, упрощает жизнь

2017-10-02 02:41 UTC, VMAtm commented on hw1/Trie/Trie/Trie.cs
> +            _size++;
Здесь и далее: так как текущее значение переменной никому не требуется, можно писать так: `++_size;` (этот момент упомянут в лекциях в разделе про цикл for).

2017-10-02 02:41 UTC, VMAtm commented on hw1/Trie/Trie/Trie.cs
> +                    TrieNode newNode = new TrieNode();
Как же так - вы везде используете var, а здесь полное имя класса.

2017-10-02 02:43 UTC, VMAtm commented on hw1/Trie/Trie/TrieNode.cs
> +        {
Здесь и далее: Terminate Node - это не очень грамотно, скорее следует назвать метод IsTerminatingNode.

2017-10-02 04:03 UTC, VMAtm commented on hw1/Trie/Trie/TrieNode.cs
> +        {
Либо, если следовать алгоритму по ссылке из условия, можно использовать IsTerminal(). Или вообще превратить метод в свойство, но это уже касается привычек именования, и не особо важно.

2017-10-04 23:02 UTC, antongulikov commented on hw1/Trie/Test/Tests.cs
> +        public void TestInit()
Что объект trie просто можно создать.

2017-10-04 23:06 UTC, antongulikov commented on hw1/Trie/Trie/Main.cs
> +    public class MainClass
А как это сделать минимальным количеством усилий?

2017-10-13 03:55 UTC, VMAtm approved these changes
Оценка обновлена до 10/10

2017-10-13 03:55 UTC, VMAtm commented on hw1/Trie/Test/Tests.cs
> +        public void TestInit()
Ясно

2017-10-13 03:55 UTC, VMAtm commented on hw1/Trie/Trie/Main.cs
> +    public class MainClass
Правой кнопкой на проект - свойства (либо выделить его и нажать <kbd>F4</kbd> - тип проекта Class Library. В файле проекта изменится `OutputType`, станет таким:

    <OutputType>Library</OutputType>

Файл `MainClass` после этого можно удалять.

2017-10-13 05:01 UTC, VMAtm commented on hw1/Trie/Trie/Main.cs
> +    public class MainClass
Не <kbd>F4</kbd>, a <kbd>Alt</kbd>+<kbd>Enter</kbd>

2017-10-17 13:28 UTC, merged